### ISSUE TITLE
How to build Vau?

### ISSUE THREAD

**Issue by PikachuHy** [mgubi/vau#1]
It is a great idea to learn the TeXmacs codebase by rebuilding a viewer.

How can I participate in this project? 

and how to build Vau on Mac?

**Comment by mgubi** [comment]
There is an Xcode project in `platform/macos`. It works fine on my machine. But I didn't spent any time in tuning the build process. You will have to change some hardcoded paths in `platform/macos/Base.xcconfig` so that Xcode can find guile and Qt (even if Qt should not be needed).

**Comment by PikachuHy** [comment]
build success with Xcode, but run fail
```
Unable to swizzle selector startRunning of class AVCaptureSession 
ERROR: Unbound variable: format-from-suffix
ERROR: In procedure apply:
ERROR: Wrong type argument in position 1: (unbound-variable #f "Unbound variable: ~S" (format-from-suffix) #f)
(lldb) 
```

**Comment by PikachuHy** [comment]
I'm trying to write `CMakeLists.txt` for Vau.

**Comment by mgubi** [comment]
What about xmake? Seems that Darcy thinks it is better. I do not have a personal opinion. Anyway be able to use CMake would also be ok. Thanks! In Xcode you can inspect which files are actually compiled and linked, not all the sources are.

**Comment by PikachuHy** [comment]
> build success with Xcode, but run fail
> 
> ```
> Unable to swizzle selector startRunning of class AVCaptureSession 
> ERROR: Unbound variable: format-from-suffix
> ERROR: In procedure apply:
> ERROR: Wrong type argument in position 1: (unbound-variable #f "Unbound variable: ~S" (format-from-suffix) #f)
> (lldb) 
> ```

after replace all bad path, I got the output

```
Unable to swizzle selector startRunning of class AVCaptureSession 
Booting Vau kernel functionality
Booting converters
Booting partial document facilities
****** End booting init-vau.scm

```

Do I run it successfully?

**Comment by PikachuHy** [comment]
> What about xmake?

I am not familiar with xmake.

**Comment by PikachuHy** [comment]
> In Xcode you can inspect which files are actually compiled and linked, not all the sources are.

How to inspect?

**Comment by mgubi** [comment]
> build success with Xcode, but run fail
> 
> ```
> Unable to swizzle selector startRunning of class AVCaptureSession 
> ERROR: Unbound variable: format-from-suffix
> ERROR: In procedure apply:
> ERROR: Wrong type argument in position 1: (unbound-variable #f "Unbound variable: ~S" (format-from-suffix) #f)
> (lldb) 
> ```

I've just tried to build on a fresh machine and it is fine. You will have to adapt some of the hard-coded paths in `vau_main.cpp` to point to sensible defaults for you. It reads a file and output is PostScript version in the home directory. See `vau_main.cpp` for more details. This is still a mess, so feel free to clean up things and submit PR. Everybody is welcome to learn together. Ideally we should write some developer doc to document what we learned in the process.

**Comment by PikachuHy** [comment]
> It reads a file and output is PostScript version in the home directory.

the file `vau-test.ps` has been generated.

**Comment by mgubi** [comment]
You have to customise 
```
set_env ("TEXMACS_PATH", "/Users/mgubi/t/vau/resources"); //FIXME: CUSTOMIZE!
```
so that Vau can find the resources. Xcode will not proceed to install them in the default position yet.

**Comment by mgubi** [comment]
> > It reads a file and output is PostScript version in the home directory.
> 
> the file `vau-test.ps` has been generated.

You can see that there the fonts are not right yet. For some reasons Vau cannot set up font properly.

**Comment by PikachuHy** [comment]
> You can see that there the fonts are not right yet.

How to preview the `vau-test.ps` file?

**Comment by mgubi** [comment]
It is a Postscript file, so you need to convert to PDF. On the Mac it is done automatically when you open it. On other systems I do not know. Maybe we should switch to produce PDF .

**Comment by PikachuHy** [comment]
I also use Mac. Ventura 13.0

**Comment by mgubi** [comment]
Then just double click on it and it will open in Preview.

**Comment by PikachuHy** [comment]
> Starting with macOS Ventura, released this week, the built-in Preview app on Mac no longer supports PostScript (.ps) and Encapsulated PostScript (.eps) files

https://www.macrumors.com/2022/10/25/macos-ventura-preview-app-drops-postscript-support/


emmm

**Comment by mgubi** [comment]
strange. It works on my Mac and I have 13.0...

Edit: I understood. it works on my machine because I have TeXshop installed and when I double-click a PS file it will open it via TeXShop as default.

**Comment by mgubi** [comment]
I guess we should anyway move away from PS to PDF quite soon.

**Comment by PikachuHy** [comment]
hi, I successfully built Vau with CMake.

**Comment by PikachuHy** [comment]
I will submit my first PR.

**Comment by mgubi** [comment]
The build process is still not perfect, one should instruct CMake to find MuPDF. However I think this issue can be closed at the moment. PR are welcome.
